In [7]:
import torch

x = torch.empty(5,3)
print(x)

tensor([[8.9082e-39, 1.0194e-38, 9.1837e-39],
        [4.6837e-39, 9.2755e-39, 1.0837e-38],
        [8.4490e-39, 9.2755e-39, 1.0561e-38],
        [1.0469e-38, 9.9184e-39, 1.0929e-38],
        [9.9184e-39, 9.0000e-39, 1.0561e-38]])


In [8]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6113, 0.0944, 0.4053],
        [0.5184, 0.7515, 0.8818],
        [0.1489, 0.7739, 0.5821],
        [0.7251, 0.1878, 0.1752],
        [0.1729, 0.1840, 0.4932]])


In [9]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 2.0193, -0.5711,  1.4997],
        [ 0.5535,  0.2307, -0.5639],
        [-0.0825, -0.5962, -0.0684],
        [-0.6768,  0.9497,  1.3155],
        [ 0.5036, -0.7539, -0.0682]])


In [12]:
print(x.size())

torch.Size([5, 3])


In [13]:
y = torch.rand(5, 3)
print(x+y)

tensor([[ 2.5448,  0.3159,  2.4706],
        [ 1.0850,  1.1444, -0.4783],
        [ 0.5679, -0.5779,  0.6148],
        [-0.3793,  1.0112,  2.2729],
        [ 1.0143,  0.1697,  0.2020]])


In [14]:
result = torch.empty(5, 3)
torch.add(x, x+y, out = result)
print(result)

tensor([[ 4.5641, -0.2553,  3.9703],
        [ 1.6384,  1.3751, -1.0421],
        [ 0.4853, -1.1741,  0.5464],
        [-1.0561,  1.9609,  3.5884],
        [ 1.5179, -0.5842,  0.1337]])


In [15]:
print(x[:,1])

tensor([-0.5711,  0.2307, -0.5962,  0.9497, -0.7539])


In [16]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x,'\n', y,'\n', z)

tensor([[ 0.1320, -0.8601, -0.1252,  1.1478],
        [-0.6630,  0.9799,  1.4961,  0.1164],
        [ 0.1688,  0.0352,  0.6074,  0.6530],
        [-1.1358,  1.0608, -1.3614, -0.9701]]) 
 tensor([ 0.1320, -0.8601, -0.1252,  1.1478, -0.6630,  0.9799,  1.4961,  0.1164,
         0.1688,  0.0352,  0.6074,  0.6530, -1.1358,  1.0608, -1.3614, -0.9701]) 
 tensor([[ 0.1320, -0.8601, -0.1252,  1.1478, -0.6630,  0.9799,  1.4961,  0.1164],
        [ 0.1688,  0.0352,  0.6074,  0.6530, -1.1358,  1.0608, -1.3614, -0.9701]])


In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2135])
0.21348588168621063


In [18]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [19]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [21]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [22]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device = device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu", torch.double))

tensor([1.2135], device='cuda:0')
tensor([1.2135], dtype=torch.float64)


In [23]:
import torch
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [24]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [25]:
print(y.grad_fn)

In [26]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [27]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [28]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [30]:
x = torch.randn(3, requires_grad = True)

y = x*2
while y.data.norm() < 1000:
    y = y*2
print(y)

tensor([-1026.5287,   567.8647, -1517.8872], grad_fn=<MulBackward0>)


In [31]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)

print(x.grad)

tensor([4.0960e+02, 4.0960e+03, 4.0960e-01])


In [32]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [34]:
print(x.requires_grad)
y = x.detach()
print(x)
print(y)
print(y.requires_grad)
print(x.eq(y).all())

True
tensor([-0.2506,  0.1386, -0.3706], requires_grad=True)
tensor([-0.2506,  0.1386, -0.3706])
False
tensor(True)
